Homework 2
================
2026-10-03

``` r
library(tidyverse)
```

# Problem 1

## Importing and cleaning the data

``` r
nyc_subways = 
  read_csv(
    file = "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv"
  ) |> 
  janitor::clean_names() |> 
  select(line, station_name, station_latitude, station_longitude, route1:route11, entry, vending, entrance_type, ada) |> 
  mutate(
    entry = case_match(
      entry,
      "YES" ~ TRUE,
      "NO" ~ FALSE
    )
  )
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

``` r
nyc_subways
```

    ## # A tibble: 1,868 × 19
    ##    line     station_name station_latitude station_longitude route1 route2 route3
    ##    <chr>    <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  2 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  3 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  4 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  5 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  6 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  7 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  8 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  9 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ## 10 4 Avenue 53rd St                  40.6             -74.0 R      <NA>   <NA>  
    ## # ℹ 1,858 more rows
    ## # ℹ 12 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <dbl>, route9 <dbl>, route10 <dbl>, route11 <dbl>, entry <lgl>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>

The NYC subway dataset contains information on each entrance and exit
for each subway station in NYC. After cleaning, the dataset has 1868
rows and 19 columns. The variables retained are: line, station_name,
station_latitude, station_longitude, route1, route2, route3, route4,
route5, route6, route7, route8, route9, route10, route11, entry,
vending, entrance_type, ada. To clean the data, I cleaned the variable
names using `janitor::clean_names()` to make them easier to work with,
selected the variables of interest (line, station name, station latitude
/ longitude, routes served, entry, vending, entrance type, and ADA
compliance), and converted the `entry` variable from character (YES /
NO) to logical (TRUE / FALSE). These data are not tidy: route
information is spread across the eleven columns `route1` through
`route11` (with `route8` through `route11` as numeric variables and
`route1` through `route7` as character variables) so the route is stored
in column names rather than as a single variable with one value per row.

## To answer the questions:

``` r
stations = 
  nyc_subways |> 
  distinct(line, station_name)
 
ada = 
  nyc_subways |> 
  filter(ada) |> 
  distinct(line, station_name)
 
no_vending = 
  nyc_subways |> 
  filter(vending == "NO") |> 
  pull(entry)
```

There are 465 distinct stations, identified by both line and station
name. 84 of these stations are ADA compliant. The proportion of station
entrances / exits without vending that allow entrance is 0.377.

## Reformatting

``` r
# First, have to make sure that all of the route variables are character.
nyc_subways = 
  nyc_subways |> 
  mutate(
    route8 = as.character(route8),
    route9 = as.character(route9),
    route10 = as.character(route10),
    route11 = as.character(route11)
  )

# using pivot_longer() to make one route number column and one route name column
nyc_subways_longer = 
  nyc_subways |> 
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name"
  )

# To answer the questions about the A train:
a_stations = 
  nyc_subways_longer |> 
  filter(route_name == "A") |> 
  distinct(line, station_name)

a_ada = 
  nyc_subways_longer |> 
  filter(route_name == "A", ada) |> 
  distinct(line, station_name)
```

60 distinct stations serve the A train. Of these, 17 are ADA compliant.

# Problem 2

## Importing and cleaning datasets

``` r
# separate sheets for the trash wheels
mr_trash_df =
  readxl::read_excel("data/202610 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N742") |> #using the range instead of skip because of some notes coming in through the excel
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(
    year = as.numeric(year),
    sports_balls = as.integer(round(sports_balls)),
    wheel = "Mr. Trash Wheel",
    month = str_to_lower(month)
  )

prof_trash_df =
  readxl::read_excel("data/202610 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", skip = 1) |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(
    year = as.numeric(year),
    plastic_bottles = as.numeric(plastic_bottles), #Dumpster 135 had a plastic_bottles value of "dive". as.numeric() converts this to NA
    wheel = "Professor Trash Wheel",
    month = str_to_lower(month)
  )
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `plastic_bottles = as.numeric(plastic_bottles)`.
    ## Caused by warning:
    ## ! NAs introduced by coercion

``` r
gwynn_df =
  readxl::read_excel("data/202610 Trash Wheel Collection Data.xlsx", sheet = "Gwynnda the Good Wheel of the W", skip = 1) |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(
    year = as.numeric(year),
    wheel = "Gwynnda",
    month = str_to_lower(month)
  )

# combining into one trash data frame
trash_df = 
  bind_rows(mr_trash_df, prof_trash_df, gwynn_df) |> 
  relocate(wheel)
```

The `trash_df` dataframe combines the data from three trash wheels:
Mr. Trash Wheel, Professor Trash Wheel, and Gwynnda. After cleaning and
combining the three datasets, the final dataset contains 1269
observations with 15 variables. The variables retained are: wheel,
dumpster, month, year, date, weight_tons, volume_cubic_yards,
plastic_bottles, polystyrene, cigarette_butts, glass_bottles,
plastic_bags, wrappers, sports_balls, homes_powered. Key variables
include `wheel`, which identifies the trash wheel, `weight_tons` and
`volume_cubic_yards` for each dumpster, and counts of items collected
such as `plastic_bottles`, `cigarette_butts`, and `wrappers`. Not every
item is recorded for every wheel: `sports_balls` is only recorded for
Mr. Trash Wheel and `glass_bottles` is not recorded for Gwynnda, so
these are missing for the other wheels.

The total weight collected by Professor Trash Wheel is 294.96 tons.
Gwynnda collected a total of 18,120 cigarette butts in June of 2022.

# Problem 3

## Baseline Data File

``` r
# full file (includes people who are excluded from the study)
baseline_df_raw = 
  read_csv("data/data_mci/MCI_baseline.csv", skip = 1, na = c("", "NA", ".")) |> 
  janitor::clean_names() |> 
  mutate(
    sex = case_match(
      sex, 1 ~ "Male", 
      0 ~ "Female"
    ),
    apoe4 = case_match(
      apoe4, 
      1 ~ "carrier",
      0 ~ "non-carrier"
    )
  )
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# excluding those with MCI at baseline
baseline_df = 
  baseline_df_raw |> 
  filter(is.na(age_at_onset) | age_at_onset > current_age)
```

``` r
# These codes are for the descriptives that are not as easy to show in just inline code

# for number who developed MCI
mci_bl =
  baseline_df |> filter(!is.na(age_at_onset))

#for the proportion of women who are APOE4 carriers
women_apoe4 = 
  baseline_df |> 
  filter(sex == "Female") |> 
  mutate(
    carrier_logic = case_match(
      apoe4,
      "carrier" ~ TRUE,
      "non-carrier" ~ FALSE
    )
  )
```

The `baseline_df` data frame contains baseline information on 479
patients without MCI at baseline. To create this dataset, I imported the
raw file, defined the NA values, skipped the first line of information
about the dataset, cleaned the names, recoded sex and APOE4 so they were
not numeric using the key that I dropped on import, and filtered out the
patients that had MCI at baseline. A total of 483 patients were
recruited, of which 479 did not have MCI at baseline (met inclusion
criteria and were thus eligible). Of these patients, 93 developed MCI.

The average age at baseline of these patients is 65.03 and the
proportion of women who are APOE4 carriers in the study is 0.3.

## Longitudinally-Observed Biomarkers Dataset

``` r
amyloid_df = 
  read_csv("data/data_mci/mci_amyloid.csv", skip = 1, na = c("", "NA", ".", "Na")) |> 
  janitor::clean_names() |> 
  pivot_longer(
    baseline:time_8,
    names_to = "time",
    names_prefix = "time_",
    values_to = "amyloid_ratio"
  ) |> 
  mutate(
    time = replace(time, time == "baseline", 0), 
    time = as.numeric(time),
    amyloid_ratio = as.numeric(amyloid_ratio)
  ) |> 
  rename(id=study_id)
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): Study ID, Baseline, Time 2, Time 4, Time 6, Time 8
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

For the dataset of longitudinally observed biomarker values, I imported
the data file, defined NAs (specifically, defined “Na” as an NA value),
cleaned the names, pivoted the time columns, and converted the time and
amyloid ratio columns to numeric values. This dataset has 2435 rows and
three columns (study id, time, and amyloid ratio). Time has values of 0
(baseline), 2, 4, 6, or 8 years, referring to the time in years that
elapsed since the study baseline to the visit where the biomarker
Amyloid 42/40 ratio was measured. The average amyloid ratio is 0.11.

## Comparing the values in the two datasets

``` r
# data frames for those who only show up in one of the two datasets
baseline_only_df = 
  baseline_df |> 
  filter(!id %in% pull(amyloid_df, id))

amyloid_only_df = 
  amyloid_df |> 
  filter(!id %in% pull(baseline_df, id)) |> 
  distinct(id)

# combined dataset of those in both
mci_df = 
  baseline_df |> 
  filter(id %in% pull(amyloid_df, id)) |> 
  left_join(amyloid_df, by = "id")

write_csv(mci_df, "data/mci_combined.csv")
```

Comparing the two datasets, 8 participants appear only in the baseline
data (so they have no amyloid measurements), and 16 appear only in the
amyloid data. The combined dataset retains the 471 participants who
appear in both, with 2355 rows (one per participant per visit) and 8
variables: id, current_age, sex, education, apoe4, age_at_onset, time,
amyloid_ratio. 167 rows have a missing amyloid ratio.
